/**
 * Small built-in pool of common English given names and surnames.
 * Hand-written for this package; intentionally tiny (no external dataset).
 */

export const FIRST_NAMES: readonly string[] = [
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Susan",
    "Richard",
    "Jessica",
    "Joseph",
    "Sarah",
    "Thomas",
    "Karen",
    "Daniel",
    "Nancy",
    "Matthew",
    "Emily",
    "Andrew",
    "Laura",
    "Kevin",
    "Rachel",
];

export const LAST_NAMES: readonly string[] = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Wilson",
    "Anderson",
    "Taylor",
    "Thomas",
    "Moore",
    "Martin",
    "Jackson",
    "Thompson",
    "White",
    "Harris",
    "Clark",
    "Lewis",
    "Walker",
    "Hall",
    "Young",
    "King",
    "Wright",
    "Scott",
];
